#!/bin/bash

# Copyright (c) 2017 HyungSeok Han and Sang Kil Cha at SoftSec, KAIST
#
# See the file LICENCE for copying permission.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IMF_DIR=$DIR/src
PYTHONPATH=$IMF_DIR:$PYTHONPATH pypy $IMF_DIR/filter.py "$@"
